#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running biome format, lint, and fix..."

# Run biome commands on src directory
npx biome format --write ./src || exit 0
npx biome lint --write ./src || exit 0

echo "Biome processing completed"

# Add any changes back to staging
git add src/
echo "Done"
